# Pandas 练习（参考答案）

本作业使用本章数据目录下的两个文件：`data/company_annual_operations_clean.xlsx` 和 `data/financial_indicators_dirty.xlsx`。

## 阶段 1 练习：数据读取与初步查看

### 练习 1.1：查看经营表结构

读取 `company_annual_operations_clean.xlsx`，赋值给变量 `annual_ex1`。显示前 5 行和后 5 行，显示行列数、列名列表和各列数据类型。

In [1]:
import pandas as pd
import numpy as np

annual_ex1 = pd.read_excel("data/company_annual_operations_clean.xlsx")

display(annual_ex1.head())
display(annual_ex1.tail())
print(annual_ex1.shape)
print(annual_ex1.columns.tolist())
display(annual_ex1.dtypes)

,证券代码,股票简称,统计截止日期,年报公布日期,行业名称,所属省份,所属城市,首次上市日期,上市状态,总资产_亿元,总负债_亿元,营业收入_亿元,营业成本_亿元,销售费用_亿元,净利润_亿元,经营现金流_亿元,资产负债率,营业毛利率,员工数目
0,2,万科A,2018-12-31,2019-03-26,房地产业,广东省,深圳市,1991-01-29,正常上市,15285.79,12929.59,2976.79,1861.04,78.68,492.72,336.18,0.845856,0.374816,104300
1,2,万科A,2019-12-31,2020-03-18,房地产业,广东省,深圳市,1991-01-29,正常上市,17299.29,14593.50,3678.94,2345.50,90.44,551.32,456.87,0.843590,0.362451,131505
2,2,万科A,2020-12-31,2021-03-31,房地产业,广东省,深圳市,1991-01-29,正常上市,18691.77,15193.33,4191.12,2965.41,106.37,592.98,531.88,0.812835,0.292454,140565
3,4,国农科技,2018-12-31,2019-04-26,医药制造业,广东省,深圳市,1991-01-14,正常上市,3.51,1.68,3.67,0.66,2.71,-0.22,-0.53,0.477966,0.818792,210
4,4,国农科技,2019-12-31,2020-04-28,软件和信息技术服务业,广东省,深圳市,1991-01-14,正常上市,14.94,0.90,1.08,0.29,0.83,-0.04,-0.16,0.060243,0.730102,251

,证券代码,股票简称,统计截止日期,年报公布日期,行业名称,所属省份,所属城市,首次上市日期,上市状态,总资产_亿元,总负债_亿元,营业收入_亿元,营业成本_亿元,销售费用_亿元,净利润_亿元,经营现金流_亿元,资产负债率,营业毛利率,员工数目
64,638,万方发展,2019-12-31,2020-06-29,软件和信息技术服务业,吉林省,白山市,1996-11-26,正常上市,5.28,3.03,1.16,0.62,0.11,0.16,0.04,0.573844,0.461441,466
65,638,万方发展,2020-12-31,2021-04-14,软件和信息技术服务业,吉林省,白山市,1996-11-26,正常上市,5.07,3.39,1.11,0.80,0.13,-0.20,-0.02,0.668138,0.277661,670
66,682,东方电子,2018-12-31,2019-04-02,电气机械及器材制造业,山东省,烟台市,1997-01-21,正常上市,51.55,18.73,30.42,20.58,3.58,2.23,2.66,0.363459,0.323683,4564
67,682,东方电子,2019-12-31,2020-04-15,软件和信息技术服务业,山东省,烟台市,1997-01-21,正常上市,62.61,27.04,34.19,22.27,4.30,2.83,5.09,0.431899,0.348472,5087
68,682,东方电子,2020-12-31,2021-04-23,软件和信息技术服务业,山东省,烟台市,1997-01-21,正常上市,68.98,30.97,37.19,24.40,4.52,3.17,3.20,0.448873,0.343719,5665

(69, 19)
['证券代码', '股票简称', '统计截止日期', '年报公布日期', '行业名称', '所属省份', '所属城市', '首次上市日期', '上市状态', '总资产_亿元', '总负债_亿元', '营业收入_亿元', '营业成本_亿元', '销售费用_亿元', '净利润_亿元', '经营现金流_亿元', '资产负债率', '营业毛利率', '员工数目']

证券代码                 int64
股票简称                object
统计截止日期      datetime64[ns]
年报公布日期      datetime64[ns]
行业名称                object
所属省份                object
所属城市                object
首次上市日期      datetime64[ns]
上市状态                object
总资产_亿元             float64
总负债_亿元             float64
营业收入_亿元            float64
营业成本_亿元            float64
销售费用_亿元            float64
净利润_亿元             float64
经营现金流_亿元           float64
资产负债率              float64
营业毛利率              float64
员工数目                 int64
dtype: object

### 练习 1.2：查看数值列的概况

继续使用 `annual_ex1`。显示 `info()` 和 `describe()` 的结果，观察这张表中有哪些列是数值列、哪些列是日期或文本列。

In [2]:
annual_ex1.info()
display(annual_ex1.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   证券代码      69 non-null     int64
 1   股票简称      69 non-null     object
 2   统计截止日期    69 non-null     datetime64[ns]
 3   年报公布日期    69 non-null     datetime64[ns]
 4   行业名称      69 non-null     object
 5   所属省份      69 non-null     object
 6   所属城市      69 non-null     object
 7   首次上市日期    69 non-null     datetime64[ns]
 8   上市状态      69 non-null     object
 9   总资产_亿元    69 non-null     float64
 10  总负债_亿元    69 non-null     float64
 11  营业收入_亿元   69 non-null     float64
 12  营业成本_亿元   69 non-null     float64
 13  销售费用_亿元   69 non-null     float64
 14  净利润_亿元    69 non-null     float64
 15  经营现金流_亿元  69 non-null     float64
 16  资产负债率     69 non-null     float64
 17  营业毛利率     69 non-null     float64
 18  员工数目      69 non-null     int64
dtypes: datetime64[ns](3), float64(9), int64(2), object(5)
memory usage: 10.4+ KB

,证券代码,统计截止日期,年报公布日期,首次上市日期,总资产_亿元,总负债_亿元,营业收入_亿元,营业成本_亿元,销售费用_亿元,净利润_亿元,经营现金流_亿元,资产负债率,营业毛利率,员工数目
count,69.000000,69,69,69,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000
mean,231.391304,2019-12-31 08:00:00,2020-04-11 01:23:28.695652096,1995-12-13 12:31:18.260869504,1072.958841,830.097101,432.114203,318.185217,25.862174,42.714928,45.986087,0.529275,0.287737,18871.782609
min,2.000000,2018-12-31 00:00:00,2019-03-14 00:00:00,1991-01-14 00:00:00,3.510000,0.900000,1.080000,0.290000,0.050000,-4.450000,-32.300000,0.060243,0.047006,148.000000
25%,16.000000,2018-12-31 00:00:00,2019-04-26 00:00:00,1992-04-28 00:00:00,36.360000,11.730000,21.580000,13.870000,0.520000,0.610000,0.040000,0.428987,0.139792,1132.000000
50%,70.000000,2019-12-31 00:00:00,2020-04-17 00:00:00,1994-04-08 00:00:00,109.500000,59.090000,57.060000,38.410000,2.560000,3.820000,2.660000,0.546613,0.217983,5504.000000
75%,423.000000,2020-12-31 00:00:00,2021-03-27 00:00:00,1997-01-21 00:00:00,168.060000,91.530000,172.490000,158.350000,8.590000,8.030000,11.240000,0.668138,0.387866,13432.000000
max,682.000000,2020-12-31 00:00:00,2021-04-30 00:00:00,2013-09-18 00:00:00,18691.770000,15193.330000,4191.120000,2965.410000,346.110000,592.980000,531.880000,0.845856,0.818792,149239.000000
std,241.802558,NaN,NaN,NaN,3536.242848,2932.349725,943.093430,662.067112,67.568613,121.331625,117.440794,0.183316,0.190411,35995.124995

## 阶段 2 练习：行列选择与条件筛选

### 练习 2.1：找出低负债且盈利的公司

在 `annual_ex1` 中筛选同时满足以下条件的公司年度记录：`净利润_亿元 > 0`、`资产负债率 < 0.6`。结果赋值给变量 `low_debt_profit`，只保留 `股票简称`、`统计截止日期`、`营业收入_亿元`、`净利润_亿元`、`资产负债率` 五列。显示结果行数，并显示前 5 行。

In [3]:
low_debt_profit = annual_ex1.loc[
    (annual_ex1["净利润_亿元"] > 0) & (annual_ex1["资产负债率"] < 0.6),
    ["股票简称", "统计截止日期", "营业收入_亿元", "净利润_亿元", "资产负债率"],
]

print(len(low_debt_profit))
display(low_debt_profit.head())

37

   股票简称     统计截止日期  营业收入_亿元  净利润_亿元     资产负债率
5  国华网安 2020-12-31     2.81    0.62  0.068264
6  深振业A 2018-12-31    25.12    9.23  0.528236
7  深振业A 2019-12-31    37.31    8.43  0.544612
8  深振业A 2020-12-31    29.35    9.03  0.492185
9  深物业A 2018-12-31    27.87    5.93  0.425931

### 练习 2.2：找出 2020 年资产规模较大的公司

在 `annual_ex1` 中筛选 2020 年、`总资产_亿元 > 1000` 的公司年度记录，赋值给变量 `large_asset_2020`。显示 `股票简称`、`行业名称`、`总资产_亿元`、`资产负债率` 四列，并查看前 5 行和后 5 行。

In [4]:
large_asset_2020 = annual_ex1.loc[
    (annual_ex1["统计截止日期"].dt.year == 2020) & (annual_ex1["总资产_亿元"] > 1000),
    ["股票简称", "行业名称", "总资产_亿元", "资产负债率"],
]

display(large_asset_2020.head())
display(large_asset_2020.tail())

    股票简称        行业名称    总资产_亿元     资产负债率
2    万科A        房地产业  18691.77  0.812835
41  美的集团  电气机械及器材制造业   3603.83  0.655263
44  潍柴动力       汽车制造业   2707.50  0.702924

    股票简称        行业名称    总资产_亿元     资产负债率
2    万科A        房地产业  18691.77  0.812835
41  美的集团  电气机械及器材制造业   3603.83  0.655263
44  潍柴动力       汽车制造业   2707.50  0.702924

## 阶段 3 练习：变量生成与数据修改

### 练习 3.1：生成分析变量

把 `annual_ex1` 复制为 `annual_ex3`。在 `annual_ex3` 中生成 `年份` 和 `净利率`。`年份` 来自 `统计截止日期` 的年份部分；`净利率 = 净利润_亿元 / 营业收入_亿元`。显示 `股票简称`、`统计截止日期`、`年份`、`营业收入_亿元`、`净利润_亿元`、`净利率` 六列的前 8 行。

In [5]:
annual_ex3 = annual_ex1.copy()
annual_ex3["年份"] = annual_ex3["统计截止日期"].dt.year
annual_ex3["净利率"] = annual_ex3["净利润_亿元"] / annual_ex3["营业收入_亿元"]

display(annual_ex3[["股票简称", "统计截止日期", "年份", "营业收入_亿元", "净利润_亿元", "净利率"]].head(8))

   股票简称     统计截止日期    年份  营业收入_亿元  净利润_亿元       净利率
0   万科A 2018-12-31  2018  2976.79  492.72  0.165521
1   万科A 2019-12-31  2019  3678.94  551.32  0.149858
2   万科A 2020-12-31  2020  4191.12  592.98  0.141485
3  国农科技 2018-12-31  2018     3.67   -0.22 -0.059946
4  国农科技 2019-12-31  2019     1.08   -0.04 -0.037037
5  国华网安 2020-12-31  2020     2.81    0.62  0.220641
6  深振业A 2018-12-31  2018    25.12    9.23  0.367436
7  深振业A 2019-12-31  2019    37.31    8.43  0.225945

### 练习 3.2：按条件生成负债水平

在 `annual_ex3` 中新增 `负债水平`。规则是：`资产负债率 >= 0.7` 记为“较高”，其他记录记为“正常”。先全部赋值为“正常”，再用 `.loc` 把符合条件的行改为“较高”。显示 `股票简称`、`年份`、`资产负债率`、`负债水平` 四列的前 8 行。

In [6]:
annual_ex3["负债水平"] = "正常"
annual_ex3.loc[annual_ex3["资产负债率"] >= 0.7, "负债水平"] = "较高"

display(annual_ex3[["股票简称", "年份", "资产负债率", "负债水平"]].head(8))

   股票简称    年份     资产负债率 负债水平
0   万科A  2018  0.845856   较高
1   万科A  2019  0.843590   较高
2   万科A  2020  0.812835   较高
3  国农科技  2018  0.477966   正常
4  国农科技  2019  0.060243   正常
5  国华网安  2020  0.068264   正常
6  深振业A  2018  0.528236   正常
7  深振业A  2019  0.544612   正常

### 练习 3.3：生成 2020 年收入排名

从 `annual_ex3` 中筛选 2020 年记录，赋值给变量 `annual_2020_ex3`。按 `营业收入_亿元` 从高到低排序，并生成 `收入排名`。`收入排名` 表示 2020 年公司营业收入从高到低的名次，收入最高为第 1 名。显示 `股票简称`、`营业收入_亿元`、`净利润_亿元`、`收入排名` 四列的前 10 行。

In [7]:
annual_2020_ex3 = annual_ex3.loc[annual_ex3["年份"] == 2020].copy()
annual_2020_ex3 = annual_2020_ex3.sort_values("营业收入_亿元", ascending=False)
annual_2020_ex3["收入排名"] = annual_2020_ex3["营业收入_亿元"].rank(ascending=False, method="min").astype(int)

display(annual_2020_ex3[["股票简称", "营业收入_亿元", "净利润_亿元", "收入排名"]].head(10))

    股票简称  营业收入_亿元  净利润_亿元  收入排名
2    万科A  4191.12  592.98     1
41  美的集团  2842.21  275.07     2
44  潍柴动力  1974.91  112.75     3
17  深康佳A   503.52    5.40     4
56  江铃汽车   330.96    5.51     5
32  德赛电池   193.98    7.40     6
23   深科技   149.67    9.53     7
47  许继电气   111.91    8.03     8
26  富奥股份   111.13    9.08     9
62  万向钱潮   108.82    4.44    10

## 阶段 4 练习：常见数据问题处理

### 练习 4.1：清洗证券代码和日期

重新读取 `financial_indicators_dirty.xlsx`，读取时把 `证券代码` 处理成字符串，赋值给变量 `dirty_indicators_ex4`。去掉 `证券代码` 和 `股票简称` 两端空格，把 `证券代码` 补齐为 6 位。把 `统计截止日期` 转成日期类型，并显示转换失败的记录。这里的日期类型表示 pandas 能识别年、月、日，后面可以继续提取年份。

In [8]:
dirty_indicators_ex4 = pd.read_excel(
    "data/financial_indicators_dirty.xlsx",
    converters={"证券代码": str},
)

dirty_indicators_ex4["证券代码"] = dirty_indicators_ex4["证券代码"].str.strip().str.zfill(6)
dirty_indicators_ex4["股票简称"] = dirty_indicators_ex4["股票简称"].str.strip()
dirty_indicators_ex4["统计截止日期"] = pd.to_datetime(dirty_indicators_ex4["统计截止日期"], errors="coerce")

display(dirty_indicators_ex4.loc[dirty_indicators_ex4["统计截止日期"].isna()])

     证券代码  股票简称 统计截止日期 加权平均净资产收益率  扣非净资产收益率  基本每股收益 非经常性损益_亿元  扣非净利润_亿元
3  000004  国农科技    NaT        -17    -19.29 -0.2414      0.03     -0.23

### 练习 4.2：清理财务指标数值列

把 `加权平均净资产收益率`、`扣非净资产收益率`、`基本每股收益`、`非经常性损益_亿元`、`扣非净利润_亿元` 转成数值列。处理百分号、逗号、`--`、`缺失` 和空字符串。显示转换后的数据类型，并显示这几列的前 8 行。

In [9]:
number_cols = [
    "加权平均净资产收益率",
    "扣非净资产收益率",
    "基本每股收益",
    "非经常性损益_亿元",
    "扣非净利润_亿元",
]

for col in number_cols:
    text = (
        dirty_indicators_ex4[col]
        .astype("string")
        .str.strip()
        .str.replace(",", "", regex=False)
        .str.replace("%", "", regex=False)
        .replace({"--": pd.NA, "缺失": pd.NA, "": pd.NA})
    )
    dirty_indicators_ex4[col] = pd.to_numeric(text, errors="coerce")

display(dirty_indicators_ex4[number_cols].dtypes)
display(dirty_indicators_ex4[["证券代码", "股票简称"] + number_cols].head(8))

加权平均净资产收益率    Float64
扣非净资产收益率      Float64
基本每股收益        Float64
非经常性损益_亿元     Float64
扣非净利润_亿元      Float64
dtype: object

     证券代码  股票简称  加权平均净资产收益率  扣非净资产收益率  基本每股收益  非经常性损益_亿元  扣非净利润_亿元
0  000002   万科A       23.24     23.05    3.06       2.83     334.9
1  000002   万科A       22.47     22.14    3.47       5.58    383.14
2  000002   万科A       20.13     19.51    3.62      12.78    402.38
3  000004  国农科技       -17.0    -19.29 -0.2414       0.03     -0.23
4  000004  国农科技        2.97    -24.12  0.0369       <NA>     -0.27
5  000004  国华网安        4.54      4.42  0.3915       0.02      0.63
6  000006  深振业A       14.86      14.8  0.6476       0.04      8.71
7  000006  深振业A       12.39      <NA>  0.5935       0.22      7.79

### 练习 4.3：删除重复记录和关键缺失

按 `证券代码` 和 `统计截止日期` 删除重复记录，再删除这两个连接键缺失的记录，结果赋值给变量 `indicators_clean_ex4`。用 `扣非净利润_亿元 > 0` 生成 `扣非盈利`，表示扣除非经常性损益后的净利润是否为正。显示清理后的行数、每列缺失值数量，并显示前 5 行。

In [10]:
indicators_clean_ex4 = (
    dirty_indicators_ex4
    .drop_duplicates(subset=["证券代码", "统计截止日期"])
    .dropna(subset=["证券代码", "统计截止日期"])
    .copy()
)
indicators_clean_ex4["扣非盈利"] = indicators_clean_ex4["扣非净利润_亿元"] > 0

print(len(indicators_clean_ex4))
display(indicators_clean_ex4.isna().sum())
display(indicators_clean_ex4.head())

44

证券代码          0
股票简称          0
统计截止日期        0
加权平均净资产收益率    0
扣非净资产收益率      1
基本每股收益        1
非经常性损益_亿元     1
扣非净利润_亿元      0
扣非盈利          0
dtype: int64

,证券代码,股票简称,统计截止日期,加权平均净资产收益率,扣非净资产收益率,基本每股收益,非经常性损益_亿元,扣非净利润_亿元,扣非盈利
0,000002,万科A,2018-12-31,23.24,23.05,3.06,2.83,334.9,True
1,000002,万科A,2019-12-31,22.47,22.14,3.47,5.58,383.14,True
2,000002,万科A,2020-12-31,20.13,19.51,3.62,12.78,402.38,True
4,000004,国农科技,2019-12-31,2.97,-24.12,0.0369,<NA>,-0.27,False
5,000004,国华网安,2020-12-31,4.54,4.42,0.3915,0.02,0.63,True

## 阶段 5 练习：表的追加与合并

### 练习 5.1：纵向追加年度经营记录

重新读取 `company_annual_operations_clean.xlsx`，读取时把 `证券代码` 处理成 6 位字符串，并把 `股票简称` 重命名为 `证券简称`。把 2018-2019 年记录和 2020 年记录拆成两张表，再用 `concat()` 追加回一张表，赋值给变量 `annual_panel_ex5`。显示 `证券代码`、`证券简称`、`统计截止日期`、`营业收入_亿元` 的前 5 行和后 5 行。

In [11]:
annual_for_merge_ex5 = pd.read_excel(
    "data/company_annual_operations_clean.xlsx",
    converters={"证券代码": lambda x: str(x).strip().zfill(6)},
).rename(columns={"股票简称": "证券简称"})

annual_2018_2019_ex5 = annual_for_merge_ex5.loc[annual_for_merge_ex5["统计截止日期"].dt.year.isin([2018, 2019])]
annual_2020_ex5 = annual_for_merge_ex5.loc[annual_for_merge_ex5["统计截止日期"].dt.year == 2020]
annual_panel_ex5 = pd.concat([annual_2018_2019_ex5, annual_2020_ex5], ignore_index=True)

display(annual_panel_ex5[["证券代码", "证券简称", "统计截止日期", "营业收入_亿元"]].head())
display(annual_panel_ex5[["证券代码", "证券简称", "统计截止日期", "营业收入_亿元"]].tail())

     证券代码  证券简称     统计截止日期  营业收入_亿元
0  000002   万科A 2018-12-31  2976.79
1  000002   万科A 2019-12-31  3678.94
2  000004  国农科技 2018-12-31     3.67
3  000004  国农科技 2019-12-31     1.08
4  000006  深振业A 2018-12-31    25.12

      证券代码  证券简称     统计截止日期  营业收入_亿元
64  000550  江铃汽车 2020-12-31   330.96
65  000555  神州信息 2020-12-31   106.86
66  000559  万向钱潮 2020-12-31   108.82
67  000638  万方发展 2020-12-31     1.11
68  000682  东方电子 2020-12-31    37.19

### 练习 5.2：合并清洗后的指标表

把 `annual_panel_ex5` 和 `indicators_clean_ex4` 按 `证券代码`、`统计截止日期` 左连接，赋值给变量 `analysis_ex5`。显示 `证券代码`、`证券简称`、`统计截止日期`、`营业收入_亿元`、`基本每股收益` 的前 8 行。

In [12]:
analysis_ex5 = annual_panel_ex5.merge(
    indicators_clean_ex4[["证券代码", "统计截止日期", "基本每股收益", "扣非净利润_亿元", "扣非盈利"]],
    on=["证券代码", "统计截止日期"],
    how="left",
)

display(analysis_ex5[["证券代码", "证券简称", "统计截止日期", "营业收入_亿元", "基本每股收益"]].head(8))

     证券代码  证券简称     统计截止日期  营业收入_亿元  基本每股收益
0  000002   万科A 2018-12-31  2976.79    3.06
1  000002   万科A 2019-12-31  3678.94    3.47
2  000004  国农科技 2018-12-31     3.67    <NA>
3  000004  国农科技 2019-12-31     1.08  0.0369
4  000006  深振业A 2018-12-31    25.12  0.6476
5  000006  深振业A 2019-12-31    37.31  0.5935
6  000011  深物业A 2018-12-31    27.87  0.9945
7  000011  深物业A 2019-12-31    39.62  1.3722

### 练习 5.3：比较不同合并方式

构造两张小表 `merge_left_ex5` 和 `merge_right_ex5`。左表包含 3 家公司的 `证券代码`、`证券简称`、`营业收入_亿元`；右表包含其中 2 家公司的 `证券代码` 和 `基本每股收益`，并额外加入 1 家不在左表中的公司。分别用 `how="left"`、`how="inner"`、`how="outer"` 合并这两张小表，展示三个结果。

In [13]:
merge_left_ex5 = pd.DataFrame({
    "证券代码": ["000001", "000002", "000004"],
    "证券简称": ["平安银行", "万科A", "国农科技"],
    "营业收入_亿元": [1535.42, 4191.12, 1.71],
})
merge_right_ex5 = pd.DataFrame({
    "证券代码": ["000001", "000002", "000011"],
    "基本每股收益": [1.40, 3.62, 1.34],
})

display(merge_left_ex5.merge(merge_right_ex5, on="证券代码", how="left"))
display(merge_left_ex5.merge(merge_right_ex5, on="证券代码", how="inner"))
display(merge_left_ex5.merge(merge_right_ex5, on="证券代码", how="outer"))

     证券代码  证券简称  营业收入_亿元  基本每股收益
0  000001  平安银行  1535.42    1.40
1  000002   万科A  4191.12    3.62
2  000004  国农科技     1.71     NaN

     证券代码  证券简称  营业收入_亿元  基本每股收益
0  000001  平安银行  1535.42    1.40
1  000002   万科A  4191.12    3.62

     证券代码  证券简称  营业收入_亿元  基本每股收益
0  000001  平安银行  1535.42    1.40
1  000002   万科A  4191.12    3.62
2  000004  国农科技     1.71     NaN
3  000011   NaN      NaN    1.34

## 阶段 6 练习：分组汇总与组内比较

### 练习 6.1：行业年度摘要表

把 `analysis_ex5` 复制为 `analysis_ex6`，并生成 `年份` 和 `净利率`。`年份` 来自 `统计截止日期` 的年份部分；`净利率 = 净利润_亿元 / 营业收入_亿元`。按 `行业名称` 和 `年份` 分组，计算 `公司数`、`营业收入合计_亿元`、`平均净利率`、`平均资产负债率`，赋值给变量 `industry_year_summary`。其中 `公司数` 是每组不重复公司数量，`营业收入合计_亿元` 是每组营业收入求和，两个平均指标是每组对应列的均值。把分组结果整理成普通表，并显示前 12 行。

In [14]:
analysis_ex6 = analysis_ex5.copy()
analysis_ex6["年份"] = analysis_ex6["统计截止日期"].dt.year
analysis_ex6["净利率"] = analysis_ex6["净利润_亿元"] / analysis_ex6["营业收入_亿元"]

industry_year_summary = (
    analysis_ex6
    .groupby(["行业名称", "年份"])
    .agg(
        公司数=("证券简称", "nunique"),
        营业收入合计_亿元=("营业收入_亿元", "sum"),
        平均净利率=("净利率", "mean"),
        平均资产负债率=("资产负债率", "mean"),
    )
    .reset_index()
)

display(industry_year_summary.head(12))

          行业名称    年份  公司数  营业收入合计_亿元     平均净利率   平均资产负债率
0        医药制造业  2018    4     115.78  0.082980  0.440385
1        医药制造业  2019    3      71.13  0.015705  0.378909
2        医药制造业  2020    3      77.80  0.072342  0.374612
3         房地产业  2018    4    3033.36  0.294673  0.576097
4         房地产业  2019    4    3760.25  0.159035  0.650078
5         房地产业  2020    4    4264.98  0.163302  0.650844
6        汽车制造业  2018    4    2067.20  0.063369  0.547328
7        汽车制造业  2019    4    2241.80  0.053176  0.560891
8        汽车制造业  2020    4    2525.82  0.049062  0.542482
9   电气机械及器材制造业  2018    5    2938.79  0.054690  0.575601
10  电气机械及器材制造业  2019    4    3111.43  0.065155  0.583958
11  电气机械及器材制造业  2020    4    3195.32  0.054741  0.625175

### 练习 6.2：判断公司是否高于行业平均

在 2020 年数据中，用 `groupby()` 和 `transform()` 计算每家公司所在行业的平均营业收入，生成 `行业平均收入_亿元`。再生成 `高于行业平均`。算法是：把公司自己的 `营业收入_亿元` 与 `行业平均收入_亿元` 比较，前者更大则为 `True`。显示 `行业名称`、`证券简称`、`营业收入_亿元`、`行业平均收入_亿元`、`高于行业平均`，并查看前 10 行。

In [15]:
analysis_2020_ex6 = analysis_ex6.loc[analysis_ex6["年份"] == 2020].copy()
analysis_2020_ex6["行业平均收入_亿元"] = analysis_2020_ex6.groupby("行业名称")["营业收入_亿元"].transform("mean")
analysis_2020_ex6["高于行业平均"] = analysis_2020_ex6["营业收入_亿元"] > analysis_2020_ex6["行业平均收入_亿元"]

display(analysis_2020_ex6[["行业名称", "证券简称", "营业收入_亿元", "行业平均收入_亿元", "高于行业平均"]].head(10))

                行业名称  证券简称  营业收入_亿元  行业平均收入_亿元  高于行业平均
46              房地产业   万科A  4191.12  1066.2450    True
47        软件和信息技术服务业  国华网安     2.81    36.9925   False
48              房地产业  深振业A    29.35  1066.2450   False
49              房地产业  深物业A    41.04  1066.2450   False
50              房地产业  沙河股份     3.47  1066.2450   False
51  计算机、通信和其他电子设备制造业  深康佳A   503.52   170.3000    True
52  计算机、通信和其他电子设备制造业  深华发A     6.92   170.3000   False
53  计算机、通信和其他电子设备制造业   深科技   149.67   170.3000   False
54             汽车制造业  富奥股份   111.13   631.4550   False
55  计算机、通信和其他电子设备制造业  深纺织A    21.09   170.3000   False

## 阶段 7 练习：数据重塑与结果表构造

### 练习 7.1：构造公司收入宽表

用 `pivot_table()` 把 `analysis_ex6` 整理为宽表：以 `证券代码`、`证券简称`、`行业名称` 标识每家公司，年份为列，值为 `营业收入_亿元`。结果赋值给变量 `revenue_wide_ex7`。计算 `收入增长率_2018_2020 = 2020 年营业收入 / 2018 年营业收入 - 1`，显示前 10 行。

In [16]:
revenue_wide_ex7 = analysis_ex6.pivot_table(
    index=["证券代码", "证券简称", "行业名称"],
    columns="年份",
    values="营业收入_亿元",
    aggfunc="first",
)
revenue_wide_ex7["收入增长率_2018_2020"] = revenue_wide_ex7[2020] / revenue_wide_ex7[2018] - 1

display(revenue_wide_ex7.head(10))

年份                               2018     2019     2020  收入增长率_2018_2020
证券代码   证券简称 行业名称
000002 万科A  房地产业              2976.79  3678.94  4191.12         0.407933
000004 国农科技 医药制造业                3.67      NaN      NaN              NaN
            软件和信息技术服务业            NaN     1.08      NaN              NaN
       国华网安 软件和信息技术服务业            NaN      NaN     2.81              NaN
000006 深振业A 房地产业                25.12    37.31    29.35         0.168392
000011 深物业A 房地产业                27.87    39.62    41.04         0.472551
000014 沙河股份 房地产业                 3.58     4.38     3.47        -0.030726
000016 深康佳A 计算机、通信和其他电子设备制造业   461.27   551.19   503.52         0.091595
000020 深华发A 计算机、通信和其他电子设备制造业     6.37     7.22     6.92         0.086342
000021 深科技  计算机、通信和其他电子设备制造业   160.61   132.24   149.67        -0.068115

### 练习 7.2：整理公司结果表

把 `revenue_wide_ex7` 的索引还原成普通列，赋值给变量 `company_summary_ex7`。显示 `证券代码`、`证券简称`、`行业名称`、`2018` 年营业收入、`2020` 年营业收入、`收入增长率_2018_2020` 六列的前 10 行。再把 `company_summary_ex7` 的 `证券代码` 设为索引，并显示前 5 行。

In [17]:
company_summary_ex7 = revenue_wide_ex7.reset_index()
display(company_summary_ex7[["证券代码", "证券简称", "行业名称", 2018, 2020, "收入增长率_2018_2020"]].head(10))

display(company_summary_ex7.set_index("证券代码").head())

年份    证券代码  证券简称              行业名称     2018     2020  收入增长率_2018_2020
0   000002   万科A              房地产业  2976.79  4191.12         0.407933
1   000004  国农科技             医药制造业     3.67      NaN              NaN
2   000004  国农科技        软件和信息技术服务业      NaN      NaN              NaN
3   000004  国华网安        软件和信息技术服务业      NaN     2.81              NaN
4   000006  深振业A              房地产业    25.12    29.35         0.168392
5   000011  深物业A              房地产业    27.87    41.04         0.472551
6   000014  沙河股份              房地产业     3.58     3.47        -0.030726
7   000016  深康佳A  计算机、通信和其他电子设备制造业   461.27   503.52         0.091595
8   000020  深华发A  计算机、通信和其他电子设备制造业     6.37     6.92         0.086342
9   000021   深科技  计算机、通信和其他电子设备制造业   160.61   149.67        -0.068115

年份      证券简称        行业名称     2018     2019     2020  收入增长率_2018_2020
证券代码
000002   万科A        房地产业  2976.79  3678.94  4191.12         0.407933
000004  国农科技       医药制造业     3.67      NaN      NaN              NaN
000004  国农科技  软件和信息技术服务业      NaN     1.08      NaN              NaN
000004  国华网安  软件和信息技术服务业      NaN      NaN     2.81              NaN
000006  深振业A        房地产业    25.12    37.31    29.35         0.168392

## 阶段 8 练习：公司年度面板中的时间顺序

### 练习 8.1：计算单家公司收入变化

把 `analysis_ex6` 按 `证券代码` 和 `统计截止日期` 排序，赋值给变量 `panel_ex8`。选出任意一家公司，赋值给变量 `one_company_ex8`。计算 `上一年营业收入_亿元`、`收入增加额_亿元`、`收入增长率`。其中 `上一年营业收入_亿元` 是上一行的营业收入，`收入增加额_亿元 = 本年营业收入 - 上一年营业收入`，`收入增长率 = 本年营业收入 / 上一年营业收入 - 1`。显示该公司的全部年度记录。

In [18]:
panel_ex8 = analysis_ex6.sort_values(["证券代码", "统计截止日期"]).copy()
one_code = panel_ex8["证券代码"].iloc[0]
one_company_ex8 = panel_ex8.loc[panel_ex8["证券代码"] == one_code].copy()
one_company_ex8["上一年营业收入_亿元"] = one_company_ex8["营业收入_亿元"].shift(1)
one_company_ex8["收入增加额_亿元"] = one_company_ex8["营业收入_亿元"].diff()
one_company_ex8["收入增长率"] = one_company_ex8["营业收入_亿元"].pct_change()

display(one_company_ex8[["证券代码", "证券简称", "年份", "营业收入_亿元", "上一年营业收入_亿元", "收入增加额_亿元", "收入增长率"]])

      证券代码 证券简称    年份  营业收入_亿元  上一年营业收入_亿元  收入增加额_亿元     收入增长率
0   000002  万科A  2018  2976.79         NaN       NaN       NaN
1   000002  万科A  2019  3678.94     2976.79    702.15  0.235875
46  000002  万科A  2020  4191.12     3678.94    512.18  0.139219

### 练习 8.2：在公司内部计算收入增长率

在 `panel_ex8` 中按 `证券代码` 分组，计算每家公司内部的 `上一年营业收入_亿元`、`收入增加额_亿元` 和 `收入增长率`。三个变量的定义和练习 8.1 相同，但必须在每家公司内部计算。筛选 2020 年记录，按 `收入增长率` 从高到低排序，赋值给变量 `top_growth_2020_ex8`。显示 `证券代码`、`证券简称`、`行业名称`、`营业收入_亿元`、`上一年营业收入_亿元`、`收入增加额_亿元`、`收入增长率` 的前 10 行。

In [19]:
panel_ex8["上一年营业收入_亿元"] = panel_ex8.groupby("证券代码")["营业收入_亿元"].shift(1)
panel_ex8["收入增加额_亿元"] = panel_ex8.groupby("证券代码")["营业收入_亿元"].diff()
panel_ex8["收入增长率"] = panel_ex8.groupby("证券代码")["营业收入_亿元"].pct_change()

top_growth_2020_ex8 = panel_ex8.loc[panel_ex8["年份"] == 2020].sort_values("收入增长率", ascending=False)
display(top_growth_2020_ex8[["证券代码", "证券简称", "行业名称", "营业收入_亿元", "上一年营业收入_亿元", "收入增加额_亿元", "收入增长率"]].head(10))

      证券代码  证券简称              行业名称  营业收入_亿元  上一年营业收入_亿元  收入增加额_亿元     收入增长率
47  000004  国华网安        软件和信息技术服务业     2.81        1.08      1.73  1.601852
63  000423  东阿阿胶             医药制造业    34.09       29.59      4.50  0.152078
62  000403  派林生物             医药制造业    10.50        9.16      1.34  0.146288
46  000002   万科A              房地产业  4191.12     3678.94    512.18  0.139219
64  000550  江铃汽车             汽车制造业   330.96      291.74     39.22  0.134435
60  000338  潍柴动力             汽车制造业  1974.91     1743.61    231.30  0.132656
53  000021   深科技  计算机、通信和其他电子设备制造业   149.67      132.24     17.43  0.131806
54  000030  富奥股份             汽车制造业   111.13      100.64     10.49  0.104233
61  000400  许继电气        电气机械及器材制造业   111.91      101.56     10.35  0.101910
57  000070  特发信息        电气机械及器材制造业    47.22       43.28      3.94  0.091035