# Pandas 阶段目标练习答案

## **练习 1.1**：查看财务表结构

读取 `finance_teaching_clean.xlsx`，赋值给变量 `finance_ex1`。显示前 5 行和后 5 行，打印行列数、列名列表和各列数据类型。

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 30)
pd.set_option("display.float_format", "{:.4f}".format)

finance_ex1 = pd.read_excel("data/finance_teaching_clean.xlsx")

display(finance_ex1.head())
display(finance_ex1.tail())
print("行列数：", finance_ex1.shape)
print("列名：", finance_ex1.columns.tolist())
print("数据类型：")
print(finance_ex1.dtypes)

   证券代码  证券简称    年份     总资产_亿元   营业收入_亿元   净利润_亿元  资产负债率
0     1  平安银行  2018 34185.9200 1062.1200 248.1800 0.9298
1     1  平安银行  2019 39390.7000 1268.1400 281.9500 0.9205
2     1  平安银行  2020 44685.1400 1432.4200 289.2800 0.9185
3     2   万科A  2018 15285.7900 2976.7900 492.7200 0.8459
4     2   万科A  2019 17299.2900 3678.9400 551.3200 0.8436

      证券代码  证券简称    年份     总资产_亿元   营业收入_亿元   净利润_亿元  资产负债率
79  600015  华夏银行  2019 30207.8900  827.6900 221.1500 0.9108
80  600015  华夏银行  2020 33998.1600  927.1700 215.6800 0.9169
81  600016  民生银行  2018 59948.2200 1288.9300 503.3000 0.9281
82  600016  民生银行  2019 66818.4100 1549.8200 549.2400 0.9206
83  600016  民生银行  2020 69502.3300 1667.7700 351.0200 0.9221

行列数： (84, 7)
列名： ['证券代码', '证券简称', '年份', '总资产_亿元', '营业收入_亿元', '净利润_亿元', '资产负债率']
数据类型：
证券代码         int64
证券简称        object
年份           int64
总资产_亿元     float64
营业收入_亿元    float64
净利润_亿元     float64
资产负债率      float64
dtype: object

## **练习 1.2**：查看关键财务指标的分布

在 `finance_ex1` 中选择 `营业收入_亿元`、`净利润_亿元`、`总资产_亿元`、`资产负债率` 四列，赋值给变量 `key_finance_ex1`。显示这四列的描述统计，并打印 2020 年样本行数。

In [2]:
key_finance_ex1 = finance_ex1[["营业收入_亿元", "净利润_亿元", "总资产_亿元", "资产负债率"]]

display(key_finance_ex1.describe())
print("2020 年样本行数：", len(finance_ex1[finance_ex1["年份"] == 2020]))

        营业收入_亿元   净利润_亿元     总资产_亿元   资产负债率
count   84.0000  84.0000    84.0000 84.0000
mean   560.8667  91.8493  8263.2971  0.5904
std    915.6682 173.1629 19255.0316  0.2229
min      0.4200  -4.4500     3.5100  0.0602
25%     33.0025   0.6025    84.8350  0.4723
50%    107.8400   5.7900   146.7800  0.6060
75%    586.9000  69.5200   927.3325  0.7074
max   4191.1200 595.0600 79502.1800  0.9298

2020 年样本行数： 28

## **练习 2.1**：找出低负债且盈利的公司

暂时删除 `证券代码` 列，结果赋值给变量 `finance_no_code_ex2`。筛选 2020 年同时满足以下条件的公司：`净利润_亿元 > 0`、`资产负债率 < 0.6`。结果赋值给变量 `low_debt_profit_2020`，只保留 `证券简称`、`营业收入_亿元`、`净利润_亿元`、`资产负债率` 四列，并按 `资产负债率` 从低到高排序。打印结果行数，并显示前 5 行。

In [3]:
finance_no_code_ex2 = finance_ex1.drop(columns=["证券代码"]).copy()

low_debt_profit_2020 = (
    finance_no_code_ex2.loc[
        (finance_no_code_ex2["年份"] == 2020)
        & (finance_no_code_ex2["净利润_亿元"] > 0)
        & (finance_no_code_ex2["资产负债率"] < 0.6),
        ["证券简称", "营业收入_亿元", "净利润_亿元", "资产负债率"],
    ]
    .sort_values("资产负债率")
)

print("结果行数：", len(low_debt_profit_2020))
low_debt_profit_2020.head()

结果行数： 11

    证券简称  营业收入_亿元  净利润_亿元  资产负债率
8   国华网安   2.8100  0.6200 0.0683
53  东阿阿胶  34.0900  0.4100 0.1071
32  深纺织A  21.0900  0.4300 0.2154
62  云南白药 327.4300 55.1100 0.3056
56  丽珠集团 105.2000 21.3100 0.3376

## **练习 2.2**：选出收入和资产都较高的公司

在 2020 年公司中，筛选 `营业收入_亿元` 高于当年中位数、并且 `总资产_亿元` 高于当年中位数的公司，赋值给变量 `large_revenue_asset_2020`。显示 `证券简称`、`营业收入_亿元`、`总资产_亿元`、`资产负债率`，并查看前 5 行和后 5 行。

In [4]:
finance_2020_ex2 = finance_no_code_ex2[finance_no_code_ex2["年份"] == 2020]
revenue_median_ex2 = finance_2020_ex2["营业收入_亿元"].median()
asset_median_ex2 = finance_2020_ex2["总资产_亿元"].median()

large_revenue_asset_2020 = finance_2020_ex2.loc[
    (finance_2020_ex2["营业收入_亿元"] > revenue_median_ex2)
    & (finance_2020_ex2["总资产_亿元"] > asset_median_ex2),
    ["证券简称", "营业收入_亿元", "总资产_亿元", "资产负债率"],
].sort_values("营业收入_亿元", ascending=False)

display(large_revenue_asset_2020.head())
display(large_revenue_asset_2020.tail())

    证券简称   营业收入_亿元     总资产_亿元  资产负债率
5    万科A 4191.1200 18691.7700 0.8128
47  美的集团 2857.1000  3603.8300 0.6553
50  潍柴动力 1974.9100  2707.5000 0.7029
77  浦发银行 1746.8700 79502.1800 0.9188
83  民生银行 1667.7700 69502.3300 0.9221

    证券简称  营业收入_亿元   总资产_亿元  资产负债率
20  深康佳A 503.5200 498.7600 0.7851
65  江铃汽车 330.9600 281.8500 0.6102
62  云南白药 327.4300 552.1900 0.3056
59  长虹美菱 153.8800 161.0300 0.6919
26   深科技 149.6700 216.3500 0.6298

## **练习 3.1**：找出收入高但净利率较低的公司

在 `finance_no_code_ex2` 中新增 `净利率 = 净利润_亿元 / 营业收入_亿元`。筛选 2020 年 `营业收入_亿元` 高于当年中位数、同时 `净利率` 低于当年中位数的公司，赋值给变量 `high_revenue_low_margin`。这个结果代表“规模不小、利润率相对偏低”的公司。再为 2020 年公司按营业收入生成 `收入排名`。显示 `证券简称`、`营业收入_亿元`、`净利润_亿元`、`净利率`、`收入排名`，并查看前 5 行和后 5 行。

In [5]:
finance_no_code_ex2["净利率"] = (
    finance_no_code_ex2["净利润_亿元"] / finance_no_code_ex2["营业收入_亿元"]
)

finance_2020_ex3 = finance_no_code_ex2[finance_no_code_ex2["年份"] == 2020].copy()
finance_2020_ex3["收入排名"] = (
    finance_2020_ex3["营业收入_亿元"]
    .rank(ascending=False, method="min")
    .astype(int)
)
revenue_median_ex3 = finance_2020_ex3["营业收入_亿元"].median()
margin_median_ex3 = finance_2020_ex3["净利率"].median()

high_revenue_low_margin = finance_2020_ex3.loc[
    (finance_2020_ex3["营业收入_亿元"] > revenue_median_ex3)
    & (finance_2020_ex3["净利率"] < margin_median_ex3),
    ["证券简称", "营业收入_亿元", "净利润_亿元", "净利率", "收入排名"],
].sort_values("营业收入_亿元", ascending=False)

display(high_revenue_low_margin.head())
display(high_revenue_low_margin.tail())

    证券简称  营业收入_亿元  净利润_亿元     净利率  收入排名
20  深康佳A 503.5200  5.4000  0.0107     8
65  江铃汽车 330.9600  5.5100  0.0166     9
35  德赛电池 193.9800  7.4000  0.0381    11
59  长虹美菱 153.8800 -0.7900 -0.0051    12

    证券简称  营业收入_亿元  净利润_亿元     净利率  收入排名
20  深康佳A 503.5200  5.4000  0.0107     8
65  江铃汽车 330.9600  5.5100  0.0166     9
35  德赛电池 193.9800  7.4000  0.0381    11
59  长虹美菱 153.8800 -0.7900 -0.0051    12

## **练习 3.2**：给公司打上资产规模标签

用 `pd.cut()` 根据 `总资产_亿元` 生成 `资产规模`：`0-100` 为“小”，`100-1000` 为“中”，`1000` 以上为“大”。统计 2020 年不同 `资产规模` 的公司数量，赋值给变量 `size_counts_2020`。要求输出计数结果。

In [6]:
finance_no_code_ex2["资产规模"] = pd.cut(
    finance_no_code_ex2["总资产_亿元"],
    bins=[0, 100, 1000, np.inf],
    labels=["小", "中", "大"],
)

size_counts_2020 = finance_no_code_ex2.loc[
    finance_no_code_ex2["年份"] == 2020,
    "资产规模",
].value_counts()
size_counts_2020

资产规模
中    14
小     7
大     7
Name: count, dtype: int64

## **练习 3.3**：按条件生成负债水平

在 `finance_no_code_ex2` 中新增 `负债水平`，先全部赋值为“正常”，再用 `.loc` 把 `资产负债率 >= 0.7` 的行改为“较高”。显示 `证券简称`、`年份`、`资产负债率`、`负债水平` 四列的前 8 行，并统计不同 `负债水平` 的数量。

In [7]:
finance_no_code_ex2["负债水平"] = "正常"
finance_no_code_ex2.loc[finance_no_code_ex2["资产负债率"] >= 0.7, "负债水平"] = "较高"

display(finance_no_code_ex2[["证券简称", "年份", "资产负债率", "负债水平"]].head(8))
finance_no_code_ex2["负债水平"].value_counts()

   证券简称    年份  资产负债率 负债水平
0  平安银行  2018 0.9298   较高
1  平安银行  2019 0.9205   较高
2  平安银行  2020 0.9185   较高
3   万科A  2018 0.8459   较高
4   万科A  2019 0.8436   较高
5   万科A  2020 0.8128   较高
6  国华网安  2018 0.4780   正常
7  国华网安  2019 0.0602   正常

负债水平
正常    61
较高    23
Name: count, dtype: int64

## **练习 4.1**：清洗一张带问题的小表

重新读取带代码的财务表，读取时把 `证券代码` 处理成 6 位字符串。取前 12 行，复制为 `dirty_ex1`。为练习清洗操作，加入以下情况：把第 2 行 `营业收入_亿元` 改成缺失值；把第 3 行 `净利润_亿元` 改成 `"--"`；把第 4 行 `总资产_亿元` 改成带逗号的字符串；再重复添加第 1 行。完成缺失值检查、重复行检查、去重、数值转换。最终结果赋值给变量 `dirty_ex1_clean`，要求 `总资产_亿元` 和 `净利润_亿元` 都是数值列。

In [8]:
def read_code(x):
    return str(x).strip().zfill(6)

finance_code = pd.read_excel(
    "data/finance_teaching_clean.xlsx",
    converters={"证券代码": read_code},
)
finance_code["净利率"] = finance_code["净利润_亿元"] / finance_code["营业收入_亿元"]

dirty_ex1 = finance_code.head(12).copy()
dirty_ex1[["总资产_亿元", "净利润_亿元"]] = dirty_ex1[["总资产_亿元", "净利润_亿元"]].astype("object")

dirty_ex1.loc[1, "营业收入_亿元"] = np.nan
dirty_ex1.loc[2, "净利润_亿元"] = "--"
dirty_ex1.loc[3, "总资产_亿元"] = "15,285.79"
dirty_ex1 = pd.concat([dirty_ex1, dirty_ex1.iloc[[0]]], ignore_index=True)

print("缺失值：")
display(dirty_ex1.isna().sum())
print("重复行数量：", dirty_ex1.duplicated().sum())

dirty_ex1_clean = dirty_ex1.drop_duplicates().copy()
dirty_ex1_clean["总资产_亿元"] = (
    dirty_ex1_clean["总资产_亿元"]
    .astype(str)
    .str.replace(",", "", regex=False)
)
dirty_ex1_clean["总资产_亿元"] = pd.to_numeric(dirty_ex1_clean["总资产_亿元"], errors="coerce")
dirty_ex1_clean["净利润_亿元"] = dirty_ex1_clean["净利润_亿元"].mask(
    dirty_ex1_clean["净利润_亿元"] == "--",
    np.nan,
)
dirty_ex1_clean["净利润_亿元"] = pd.to_numeric(dirty_ex1_clean["净利润_亿元"], errors="coerce")

display(dirty_ex1_clean[["总资产_亿元", "净利润_亿元"]].dtypes)
dirty_ex1_clean.head()

缺失值：

证券代码       0
证券简称       0
年份         0
总资产_亿元     0
营业收入_亿元    1
净利润_亿元     0
资产负债率      0
净利率        0
dtype: int64

重复行数量： 1

总资产_亿元    float64
净利润_亿元    float64
dtype: object

     证券代码  证券简称    年份     总资产_亿元   营业收入_亿元   净利润_亿元  资产负债率    净利率
0  000001  平安银行  2018 34185.9200 1062.1200 248.1800 0.9298 0.2337
1  000001  平安银行  2019 39390.7000       NaN 281.9500 0.9205 0.2223
2  000001  平安银行  2020 44685.1400 1432.4200      NaN 0.9185 0.2020
3  000002   万科A  2018 15285.7900 2976.7900 492.7200 0.8459 0.1655
4  000002   万科A  2019 17299.2900 3678.9400 551.3200 0.8436 0.1499

## **练习 4.2**：替换特殊值并填补缺失

在 `dirty_ex1_clean` 中，把 `净利润_亿元` 的缺失值填为 0，把 `营业收入_亿元` 的缺失值填为该列中位数。新增 `是否盈利` 列：`净利润_亿元 > 0` 为 `True`，否则为 `False`。输出每列缺失值数量，并显示 `证券简称`、`营业收入_亿元`、`净利润_亿元`、`是否盈利`。

In [9]:
dirty_ex1_clean["净利润_亿元"] = dirty_ex1_clean["净利润_亿元"].fillna(0)
dirty_ex1_clean["营业收入_亿元"] = dirty_ex1_clean["营业收入_亿元"].fillna(
    dirty_ex1_clean["营业收入_亿元"].median()
)
dirty_ex1_clean["是否盈利"] = dirty_ex1_clean["净利润_亿元"] > 0

display(dirty_ex1_clean.isna().sum())
dirty_ex1_clean[["证券简称", "营业收入_亿元", "净利润_亿元", "是否盈利"]].head()

证券代码       0
证券简称       0
年份         0
总资产_亿元     0
营业收入_亿元    0
净利润_亿元     0
资产负债率      0
净利率        0
是否盈利       0
dtype: int64

   证券简称   营业收入_亿元   净利润_亿元   是否盈利
0  平安银行 1062.1200 248.1800   True
1  平安银行   37.3100 281.9500   True
2  平安银行 1432.4200   0.0000  False
3   万科A 2976.7900 492.7200   True
4   万科A 3678.9400 551.3200   True

## **练习 4.3**：用映射生成风险标签

根据 `资产负债率` 新增 `负债水平`：大于等于 0.7 为“较高”，否则为“正常”。再用 `map()` 把“较高”映射为“需关注”，把“正常”映射为“低风险”，生成 `负债风险`。统计不同 `负债风险` 的数量。

In [10]:
dirty_ex1_clean["负债水平"] = np.where(dirty_ex1_clean["资产负债率"] >= 0.7, "较高", "正常")
debt_risk_map = {"较高": "需关注", "正常": "低风险"}
dirty_ex1_clean["负债风险"] = dirty_ex1_clean["负债水平"].map(debt_risk_map)

dirty_ex1_clean["负债风险"].value_counts()

负债风险
需关注    6
低风险    6
Name: count, dtype: int64

## **练习 5.1**：处理证券代码并合并行业信息

重新读取 `finance_teaching_clean.xlsx` 和 `company_profile_teaching_clean.xlsx`。读取时把 `证券代码` 处理成 6 位字符串。筛选 2020 年财务数据，与公司信息表按 `证券代码` 合并，赋值给变量 `finance_company_2020`。检查合并前后行数是否一致，并检查 `行业名称` 是否有缺失。

In [11]:
company_code = pd.read_excel(
    "data/company_profile_teaching_clean.xlsx",
    converters={"证券代码": read_code},
)

company_code["上市日期"] = pd.to_datetime(company_code["上市日期"])
company_code["上市年份"] = company_code["上市日期"].dt.year

finance_2020_code = finance_code[finance_code["年份"] == 2020].copy()
finance_company_2020 = finance_2020_code.merge(company_code, on=["证券代码", "证券简称"], how="left")

print("合并前行数：", len(finance_2020_code))
print("合并后行数：", len(finance_company_2020))
print("行业缺失数量：", finance_company_2020["行业名称"].isna().sum())
finance_company_2020.head()

合并前行数： 28
合并后行数： 28
行业缺失数量： 0

,证券代码,证券简称,年份,总资产_亿元,营业收入_亿元,净利润_亿元,资产负债率,净利率,行业名称,省份,城市,上市市场,上市日期,上市年份
0,000001,平安银行,2020,44685.1400,1432.4200,289.2800,0.9185,0.2020,货币金融服务,广东省,深圳市,SZSE,1991-04-03,1991
1,000002,万科A,2020,18691.7700,4191.1200,592.9800,0.8128,0.1415,房地产业,广东省,深圳市,SZSE,1991-01-29,1991
2,000004,国华网安,2020,15.6400,2.8100,0.6200,0.0683,0.2206,软件和信息技术服务业,广东省,深圳市,SZSE,1991-01-14,1991
3,000006,深振业A,2020,154.3500,29.3500,9.0300,0.4922,0.3077,房地产业,广东省,深圳市,SZSE,1992-04-27,1992
4,000007,*ST 全新,2020,3.6400,0.4500,-1.2300,0.8139,-2.7333,房地产业,广东省,深圳市,SZSE,1992-04-13,1992

## **练习 5.2**：找出制造业中收入最高的公司

在 `finance_company_2020` 中筛选 `行业名称` 包含“制造”的公司，赋值给变量 `manufacturing_2020`。按 `营业收入_亿元` 从高到低排序，显示前 8 行。结果应包含 `证券代码`、`证券简称`、`行业名称`、`省份`、`营业收入_亿元`、`净利润_亿元`。

In [12]:
manufacturing_2020 = (
    finance_company_2020.loc[
        finance_company_2020["行业名称"].str.contains("制造", na=False),
        ["证券代码", "证券简称", "行业名称", "省份", "营业收入_亿元", "净利润_亿元"],
    ]
    .sort_values("营业收入_亿元", ascending=False)
)

manufacturing_2020.head(8)

      证券代码  证券简称              行业名称   省份   营业收入_亿元   净利润_亿元
15  000333  美的集团        电气机械及器材制造业  广东省 2857.1000 275.0700
16  000338  潍柴动力             汽车制造业  山东省 1974.9100 112.7500
6   000016  深康佳A  计算机、通信和其他电子设备制造业  广东省  503.5200   5.4000
21  000550  江铃汽车             汽车制造业  江西省  330.9600   5.5100
20  000538  云南白药             医药制造业  云南省  327.4300  55.1100
11  000049  德赛电池        电气机械及器材制造业  广东省  193.9800   7.4000
19  000521  长虹美菱        电气机械及器材制造业  安徽省  153.8800  -0.7900
8   000021   深科技  计算机、通信和其他电子设备制造业  广东省  149.6700   9.5300

## **练习 5.3**：比较早上市公司和较晚上市公司

把公司表中的 `上市日期` 转为日期格式，并生成 `上市年份`。在 `finance_company_2020` 中新增 `上市阶段`：`上市年份 < 2000` 标记为“较早上市”，否则标记为“较晚上市”。分别计算两组公司的平均 `营业收入_亿元` 和平均 `净利率`。

In [13]:
finance_company_2020["上市阶段"] = np.where(
    finance_company_2020["上市年份"] < 2000,
    "较早上市",
    "较晚上市",
)

finance_company_2020.groupby("上市阶段").agg(
    平均营业收入_亿元=("营业收入_亿元", "mean"),
    平均净利率=("净利率", "mean"),
)

      平均营业收入_亿元   平均净利率
上市阶段
较早上市   457.0819 -0.0392
较晚上市  1086.6029  0.0929

## **练习 6.1**：行业年度摘要表

把财务表和公司信息表合并为 `analysis_ex6`。按 `行业名称` 和 `年份` 分组，计算 `公司数`、`营业收入合计_亿元`、`平均净利率`、`平均资产负债率`，赋值给变量 `industry_year_summary`。显示前 12 行。

In [14]:
analysis_ex6 = finance_code.merge(
    company_code[["证券代码", "行业名称", "省份"]],
    on="证券代码",
    how="left",
)

industry_year_summary = (
    analysis_ex6
    .groupby(["行业名称", "年份"])
    .agg(
        公司数=("证券简称", "nunique"),
        营业收入合计_亿元=("营业收入_亿元", "sum"),
        平均净利率=("净利率", "mean"),
        平均资产负债率=("资产负债率", "mean"),
    )
    .reset_index()
)

industry_year_summary.head(12)

          行业名称    年份  公司数  营业收入合计_亿元   平均净利率  平均资产负债率
0        医药制造业  2018    4   459.2000  0.1403   0.3560
1        医药制造业  2019    4   452.4700  0.0428   0.3292
2        医药制造业  2020    4   499.9300  0.1034   0.3380
3         房地产业  2018    4  3030.2000 -0.9802   0.6109
4         房地产业  2019    4  3756.2900  0.2717   0.6716
5         房地产业  2020    4  4261.9600 -0.5265   0.7023
6        汽车制造业  2018    4  2067.2000  0.0634   0.5473
7        汽车制造业  2019    4  2241.8000  0.0532   0.5609
8        汽车制造业  2020    4  2525.8200  0.0491   0.5425
9   电气机械及器材制造业  2018    4  3022.6500  0.0425   0.6743
10  电气机械及器材制造业  2019    4  3190.3300  0.0509   0.6272
11  电气机械及器材制造业  2020    4  3252.1800  0.0354   0.6761

## **练习 6.2**：每个行业找两家公司

在 2020 年数据中，按 `行业名称` 分组，找出每个行业 `营业收入_亿元` 最高的 2 家公司，赋值给变量 `top2_revenue_by_industry`。结果只保留 `行业名称`、`证券代码`、`证券简称`、`营业收入_亿元`、`净利率`，并按行业名称和营业收入排序。

In [15]:
top2_revenue_by_industry = (
    analysis_ex6[analysis_ex6["年份"] == 2020]
    .sort_values(["行业名称", "营业收入_亿元"], ascending=[True, False])
    .groupby("行业名称")
    .head(2)
    .loc[:, ["行业名称", "证券代码", "证券简称", "营业收入_亿元", "净利率"]]
)

top2_revenue_by_industry

                行业名称    证券代码  证券简称   营业收入_亿元    净利率
62             医药制造业  000538  云南白药  327.4300 0.1683
56             医药制造业  000513  丽珠集团  105.2000 0.2026
5               房地产业  000002   万科A 4191.1200 0.1415
17              房地产业  000011  深物业A   41.0400 0.1781
50             汽车制造业  000338  潍柴动力 1974.9100 0.0571
65             汽车制造业  000550  江铃汽车  330.9600 0.0166
47        电气机械及器材制造业  000333  美的集团 2857.1000 0.0963
35        电气机械及器材制造业  000049  德赛电池  193.9800 0.0381
20  计算机、通信和其他电子设备制造业  000016  深康佳A  503.5200 0.0107
26  计算机、通信和其他电子设备制造业  000021   深科技  149.6700 0.0637
77            货币金融服务  600000  浦发银行 1746.8700 0.3377
83            货币金融服务  600016  民生银行 1667.7700 0.2105
68        软件和信息技术服务业  000555  神州信息  106.8600 0.0436
44        软件和信息技术服务业  000158  常山北明   98.8400 0.0108

## **练习 6.3**：计算行业内部收入差距

自定义函数 `value_range(x)`，返回 `x.max() - x.min()`。按 `行业名称` 分组，计算 2020 年各行业营业收入的均值和收入差距，赋值给变量 `industry_gap_2020`。按收入差距从高到低排序。

In [16]:
def value_range(x):
    return x.max() - x.min()

industry_gap_2020 = (
    analysis_ex6[analysis_ex6["年份"] == 2020]
    .groupby("行业名称")
    .agg(
        收入均值=("营业收入_亿元", "mean"),
        收入差距=("营业收入_亿元", value_range),
    )
    .sort_values("收入差距", ascending=False)
)

industry_gap_2020

                      收入均值      收入差距
行业名称
房地产业             1065.4900 4190.6700
电气机械及器材制造业        813.0450 2809.8800
汽车制造业             631.4550 1866.0900
货币金融服务           1443.5575  819.7000
计算机、通信和其他电子设备制造业  170.3000  496.6000
医药制造业             124.9825  294.2200
软件和信息技术服务业         52.4050  105.7500

## **练习 6.4**：判断公司是否高于行业平均

在 2020 年数据中，用 `groupby()` 和 `transform()` 计算每家公司所在行业的平均营业收入，生成 `行业平均收入_亿元`。再生成 `高于行业平均`，表示该公司营业收入是否高于所在行业平均值。显示 `行业名称`、`证券简称`、`营业收入_亿元`、`行业平均收入_亿元`、`高于行业平均`，并查看前 10 行。

In [17]:
industry_compare_ex6 = analysis_ex6[analysis_ex6["年份"] == 2020].copy()
industry_compare_ex6["行业平均收入_亿元"] = (
    industry_compare_ex6
    .groupby("行业名称")["营业收入_亿元"]
    .transform("mean")
)
industry_compare_ex6["高于行业平均"] = (
    industry_compare_ex6["营业收入_亿元"] > industry_compare_ex6["行业平均收入_亿元"]
)

industry_compare_ex6[[
    "行业名称", "证券简称", "营业收入_亿元", "行业平均收入_亿元", "高于行业平均"
]].head(10)

                行业名称    证券简称   营业收入_亿元  行业平均收入_亿元  高于行业平均
2             货币金融服务    平安银行 1432.4200  1443.5575   False
5               房地产业     万科A 4191.1200  1065.4900    True
8         软件和信息技术服务业    国华网安    2.8100    52.4050   False
11              房地产业    深振业A   29.3500  1065.4900   False
14              房地产业  *ST 全新    0.4500  1065.4900   False
17              房地产业    深物业A   41.0400  1065.4900   False
20  计算机、通信和其他电子设备制造业    深康佳A  503.5200   170.3000    True
23  计算机、通信和其他电子设备制造业    深华发A    6.9200   170.3000   False
26  计算机、通信和其他电子设备制造业     深科技  149.6700   170.3000   False
29             汽车制造业    富奥股份  111.1300   631.4550   False

## **练习 7.1**：构造公司收入宽表

用 `pivot_table()` 把 `analysis_ex6` 整理为每家公司一行、年份为列、值为 `营业收入_亿元` 的宽表，赋值给变量 `revenue_wide_ex7`。计算 `收入增长率_2018_2020 = 2020 / 2018 - 1`，按增长率从高到低排序，显示前 10 行。

In [18]:
revenue_wide_ex7 = analysis_ex6.pivot_table(
    index=["证券代码", "证券简称", "行业名称"],
    columns="年份",
    values="营业收入_亿元",
)
revenue_wide_ex7["收入增长率_2018_2020"] = revenue_wide_ex7[2020] / revenue_wide_ex7[2018] - 1

revenue_wide_ex7.sort_values("收入增长率_2018_2020", ascending=False).head(10)

年份                                2018      2019      2020  收入增长率_2018_2020
证券代码   证券简称 行业名称
000045 深纺织A 计算机、通信和其他电子设备制造业   12.7200   21.5800   21.0900           0.6580
000011 深物业A 房地产业               27.8700   39.6200   41.0400           0.4726
000030 富奥股份 汽车制造业              78.5300  100.6400  111.1300           0.4151
000002 万科A  房地产业             2976.7900 3678.9400 4191.1200           0.4079
000001 平安银行 货币金融服务           1062.1200 1268.1400 1432.4200           0.3486
600015 华夏银行 货币金融服务            694.0300  827.6900  927.1700           0.3359
600016 民生银行 货币金融服务           1288.9300 1549.8200 1667.7700           0.2939
000338 潍柴动力 汽车制造业            1592.5600 1743.6100 1974.9100           0.2401
000538 云南白药 医药制造业             267.0800  296.6500  327.4300           0.2260
000513 丽珠集团 医药制造业              88.6100   93.8500  105.2000           0.1872

## **练习 7.2**：构造公司综合摘要表

基于 `analysis_ex6` 构造 `company_profile_summary`，每家公司一行，至少包含：`证券代码`、`证券简称`、`行业名称`、`省份`、`2018` 年营业收入、`2020` 年营业收入、`收入增长率_2018_2020`、`2020` 年资产负债率。按 `收入增长率_2018_2020` 从高到低排序，显示前 10 行。

In [19]:
revenue_summary = analysis_ex6.pivot_table(
    index=["证券代码", "证券简称", "行业名称", "省份"],
    columns="年份",
    values="营业收入_亿元",
).reset_index()
revenue_summary["收入增长率_2018_2020"] = revenue_summary[2020] / revenue_summary[2018] - 1

debt_2020 = analysis_ex6.loc[
    analysis_ex6["年份"] == 2020,
    ["证券代码", "资产负债率"],
].rename(columns={"资产负债率": "2020年资产负债率"})

company_profile_summary = revenue_summary.merge(debt_2020, on="证券代码", how="left")
company_profile_summary = company_profile_summary.sort_values("收入增长率_2018_2020", ascending=False)

company_profile_summary.head(10)

,证券代码,证券简称,行业名称,省份,2018,2019,2020,收入增长率_2018_2020,2020年资产负债率
10,000045,深纺织A,计算机、通信和其他电子设备制造业,广东省,12.7200,21.5800,21.0900,0.6580,0.2154
5,000011,深物业A,房地产业,广东省,27.8700,39.6200,41.0400,0.4726,0.6903
9,000030,富奥股份,汽车制造业,吉林省,78.5300,100.6400,111.1300,0.4151,0.4278
1,000002,万科A,房地产业,广东省,2976.7900,3678.9400,4191.1200,0.4079,0.8128
0,000001,平安银行,货币金融服务,广东省,1062.1200,1268.1400,1432.4200,0.3486,0.9185
26,600015,华夏银行,货币金融服务,北京市,694.0300,827.6900,927.1700,0.3359,0.9169
27,600016,民生银行,货币金融服务,北京市,1288.9300,1549.8200,1667.7700,0.2939,0.9221
16,000338,潍柴动力,汽车制造业,山东省,1592.5600,1743.6100,1974.9100,0.2401,0.7029
20,000538,云南白药,医药制造业,云南省,267.0800,296.6500,327.4300,0.2260,0.3056
18,000513,丽珠集团,医药制造业,广东省,88.6100,93.8500,105.2000,0.1872,0.3376

## **练习 7.3**：核对公司摘要表

检查 `company_profile_summary` 的行数是否等于公司数量。再按 `行业名称` 统计公司数量，并显示统计结果。最后显示 `company_profile_summary` 的前 5 行和后 5 行。

In [20]:
print("摘要表行数：", len(company_profile_summary))
print("公司数量：", analysis_ex6["证券代码"].nunique())

display(company_profile_summary["行业名称"].value_counts())
display(company_profile_summary.head())
display(company_profile_summary.tail())

摘要表行数： 28
公司数量： 28

行业名称
计算机、通信和其他电子设备制造业    4
房地产业                4
汽车制造业               4
货币金融服务              4
医药制造业               4
软件和信息技术服务业          4
电气机械及器材制造业          4
Name: count, dtype: int64

,证券代码,证券简称,行业名称,省份,2018,2019,2020,收入增长率_2018_2020,2020年资产负债率
10,000045,深纺织A,计算机、通信和其他电子设备制造业,广东省,12.7200,21.5800,21.0900,0.6580,0.2154
5,000011,深物业A,房地产业,广东省,27.8700,39.6200,41.0400,0.4726,0.6903
9,000030,富奥股份,汽车制造业,吉林省,78.5300,100.6400,111.1300,0.4151,0.4278
1,000002,万科A,房地产业,广东省,2976.7900,3678.9400,4191.1200,0.4079,0.8128
0,000001,平安银行,货币金融服务,广东省,1062.1200,1268.1400,1432.4200,0.3486,0.9185

,证券代码,证券简称,行业名称,省份,2018,2019,2020,收入增长率_2018_2020,2020年资产负债率
8,000021,深科技,计算机、通信和其他电子设备制造业,广东省,160.6100,132.2400,149.6700,-0.0681,0.6298
19,000521,长虹美菱,电气机械及器材制造业,安徽省,174.9000,165.5300,153.8800,-0.1202,0.6919
12,000070,特发信息,电气机械及器材制造业,广东省,57.0600,46.5600,47.2200,-0.1725,0.6693
2,000004,国华网安,软件和信息技术服务业,广东省,3.6700,1.0800,2.8100,-0.2343,0.0683
17,000423,东阿阿胶,医药制造业,山东省,73.3800,29.5900,34.0900,-0.5354,0.1071

## **练习 8.1**：构造价格序列并计算收益率

构造 2021 年 1 月到 2021 年 6 月的工作日日期。使用随机数生成一列日收益率 `return`，从初始价格 100 出发构造价格 `price`。把结果赋值给以日期为索引的变量 `price_df`，并新增 `lag_price`、`diff`、`pct_return` 三列。显示前 8 行。

In [21]:
dates_ex8 = pd.date_range("2021-01-01", "2021-06-30", freq="B")
rng = np.random.default_rng(2021)

price_df = pd.DataFrame(
    {"return": rng.normal(0.0004, 0.012, len(dates_ex8))},
    index=dates_ex8,
)
price_df["price"] = 100 * (1 + price_df["return"]).cumprod()
price_df["lag_price"] = price_df["price"].shift(1)
price_df["diff"] = price_df["price"].diff()
price_df["pct_return"] = price_df["price"].pct_change()

price_df.head(8)

            return   price  lag_price    diff  pct_return
2021-01-01 -0.0004 99.9574        NaN     NaN         NaN
2021-01-04 -0.0078 99.1733    99.9574 -0.7840     -0.0078
2021-01-05 -0.0091 98.2746    99.1733 -0.8987     -0.0091
2021-01-06  0.0133 99.5829    98.2746  1.3082      0.0133
2021-01-07  0.0003 99.6101    99.5829  0.0273      0.0003
2021-01-08 -0.0051 99.1053    99.6101 -0.5048     -0.0051
2021-01-11 -0.0001 99.0990    99.1053 -0.0063     -0.0001
2021-01-12 -0.0311 96.0212    99.0990 -3.0778     -0.0311

## **练习 8.2**：按月份观察价格变化

从 `price_df` 中筛选 2021 年 3 月的数据，赋值给变量 `march_price`。显示前 5 行和后 5 行。然后用 `resample("ME").last()` 得到月末价格，赋值给变量 `month_end_price_ex8`。

In [22]:
march_price = price_df.loc["2021-03"]
display(march_price.head())
display(march_price.tail())

month_end_price_ex8 = price_df["price"].resample("ME").last()
month_end_price_ex8

            return   price  lag_price    diff  pct_return
2021-03-01 -0.0088 91.7913    92.6019 -0.8106     -0.0088
2021-03-02  0.0011 91.8966    91.7913  0.1054      0.0011
2021-03-03 -0.0088 91.0898    91.8966 -0.8068     -0.0088
2021-03-04  0.0222 93.1146    91.0898  2.0248      0.0222
2021-03-05  0.0131 94.3387    93.1146  1.2241      0.0131

            return   price  lag_price    diff  pct_return
2021-03-25  0.0103 96.1285    95.1452  0.9833      0.0103
2021-03-26  0.0009 96.2115    96.1285  0.0830      0.0009
2021-03-29  0.0059 96.7795    96.2115  0.5680      0.0059
2021-03-30  0.0010 96.8716    96.7795  0.0920      0.0010
2021-03-31 -0.0002 96.8511    96.8716 -0.0205     -0.0002

2021-01-31    93.5359
2021-02-28    92.6019
2021-03-31    96.8511
2021-04-30    99.5666
2021-05-31   101.0273
2021-06-30    98.7283
Freq: ME, Name: price, dtype: float64

## **练习 8.3**：从月末价格计算月收益

基于 `month_end_price_ex8` 计算月收益率，赋值给变量 `month_return_ex8`。找出月收益率最高的月份和最低的月份，并打印对应月份和收益率。

In [23]:
month_return_ex8 = month_end_price_ex8.pct_change().dropna()

best_month = month_return_ex8.idxmax()
worst_month = month_return_ex8.idxmin()

print("月收益率最高：", best_month.strftime("%Y-%m"), month_return_ex8.loc[best_month])
print("月收益率最低：", worst_month.strftime("%Y-%m"), month_return_ex8.loc[worst_month])

month_return_ex8

月收益率最高： 2021-03 0.045886210814362505
月收益率最低： 2021-06 -0.022756644765671297

2021-02-28   -0.0100
2021-03-31    0.0459
2021-04-30    0.0280
2021-05-31    0.0147
2021-06-30   -0.0228
Freq: ME, Name: price, dtype: float64